// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQF3BqA5lNQtLo_DSTU0PPv6De1tGwx2I',
    appId: '1:349865586099:web:3ac5ef83c1c42427daefc6',
    messagingSenderId: '349865586099',
    projectId: 'ipk-mini-project',
    authDomain: 'ipk-mini-project.firebaseapp.com',
    storageBucket: 'ipk-mini-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChsEwD_PiBZS8sXfHn7intEbEgI4XHl0g',
    appId: '1:349865586099:android:7dd01fdef4719f7edaefc6',
    messagingSenderId: '349865586099',
    projectId: 'ipk-mini-project',
    storageBucket: 'ipk-mini-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO4pLaTxK9-1jVM1LsH_Da3-hGfIXhw-M',
    appId: '1:349865586099:ios:1327b9d7af15847adaefc6',
    messagingSenderId: '349865586099',
    projectId: 'ipk-mini-project',
    storageBucket: 'ipk-mini-project.appspot.com',
    iosBundleId: 'com.example.ipkKalkulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO4pLaTxK9-1jVM1LsH_Da3-hGfIXhw-M',
    appId: '1:349865586099:ios:1327b9d7af15847adaefc6',
    messagingSenderId: '349865586099',
    projectId: 'ipk-mini-project',
    storageBucket: 'ipk-mini-project.appspot.com',
    iosBundleId: 'com.example.ipkKalkulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQF3BqA5lNQtLo_DSTU0PPv6De1tGwx2I',
    appId: '1:349865586099:web:a98ed91eb4aa8b29daefc6',
    messagingSenderId: '349865586099',
    projectId: 'ipk-mini-project',
    authDomain: 'ipk-mini-project.firebaseapp.com',
    storageBucket: 'ipk-mini-project.appspot.com',
  );
}
